### ISSUE TITLE
Header files missing in /include/planner/operators/expressions.h

### ISSUE THREAD

**Issue by ctb0815** [CASP-Systems-BU/Secrecy#1]
On a fresh Ubuntu 22.04. I get several errors when compiling using ./run_test.sh due to missing header files in
/include/planner/operators/expressions.h

#include <algorithm>  // transform is not a member of 'std'
#include <memory>    //for enable_shared_from_this
#include <cassert>      //assert was not declared in this scope

**Comment by mfaisal97** [comment]
Thank you.

Issue is now fixed using commit:

https://github.com/CASP-Systems-BU/Secrecy/commit/1f05b47403aa115969e22d3bbb573058065ca09a
